language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - sudo apt-get -y install hmmer
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -e . # install package
# command to run tests
script:
  - pytest
after_success:
  - codecov
